import Head from "next/head";
import AppLayout from "./Components/appLayout";
import { BackgroundImage, Center, Flex, Space, Text } from "@mantine/core";
import Slider from "./Components/slider";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BackgroundImage src="/homePic.jpeg" h={"70vh"} w={"100%"}>
        <AppLayout withHeaderBorder={false}>
          <Flex
            direction={"column"}
            h={"40vh"}
            align={"center"}
            justify={"center"}
          >
            <Text fw={800} size="xl">
              Discover Sicilian Experiences: Find Local Adventures in Your City
            </Text>

            <h1> TODO SEARCH</h1>
          </Flex>
        </AppLayout>
      </BackgroundImage>
      <Space h={"xl"} />
      <Slider />
      <Space h={"xl"} />
      <Space h={"xl"} />
      <Space h={"xl"} />
      <Space h={"xl"} />
    </>
  );
}
